EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_DIM = 384

CHUNK_SIZE = 400
CHUNK_OVERLAP = 80

TOP_K = 5
COLLECTION_NAME = "documents"

GEMINI_MODEL = "gemini-2.5-flash"
MAX_TOKENS = 1024

CONFIDENCE_HIGH = 0.45
CONFIDENCE_MEDIUM = 0.30
